# Generated by Django 3.2.19 on 2023-09-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('numero_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=9)),
                ('fecha_transaccion', models.CharField(max_length=19, null=True)),
                ('monto_compra', models.IntegerField()),
                ('estado', models.CharField(choices=[('CANCELADA', 'CANCELADA'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=9, null=True)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=50)),
                ('correo_cliente', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('marca', models.CharField(max_length=40)),
                ('existencia_actual', models.BooleanField(default=False)),
                ('codigo_familia', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rut_proveedor', models.CharField(max_length=9, null=True)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('apellido_proveedor', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=50, null=True)),
                ('telefono_proveedor', models.CharField(max_length=50, null=True)),
                ('correo_proveedor', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.CharField(max_length=19, null=True)),
                ('total_venta', models.IntegerField()),
                ('es_credito', models.BooleanField(default=False)),
                ('productos_vendidos', models.ManyToManyField(through='web_yuyitos.DetalleVenta', to='web_yuyitos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_yuyitos.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_yuyitos.venta'),
        ),
    ]
